import { DeckData } from '@/lib/supabase-client'

const now = new Date('2026-02-15T00:00:00.000Z').toISOString()

export const localPrebuiltDecks: DeckData[] = [
  {
    id: 'prebuilt-ai-ethics-2026',
    title: 'AI Ethics 2026',
    description: 'Core ethical risks, safeguards, and governance patterns for modern AI systems.',
    createdAt: now,
    updatedAt: now,
    cards: [
      {
        id: 'ai-ethics-1',
        hook: 'Consent First',
        meat: 'Collect and use data only with clear consent and a stated purpose. Hidden collection breaks trust and can violate law.',
        simplified: 'Ask permission before using data and say why you need it.',
        category: 'Principles',
        difficulty: 'beginner',
      },
      {
        id: 'ai-ethics-2',
        hook: 'Bias Check',
        meat: 'Models can amplify historical bias. Test across groups and fix gaps before deployment.',
        simplified: 'Check if the system treats groups unfairly and fix it.',
        category: 'Risk',
        difficulty: 'intermediate',
      },
      {
        id: 'ai-ethics-3',
        hook: 'Explain It',
        meat: 'People need understandable reasons for high-stakes outcomes. Use summaries, examples, and limits.',
        simplified: 'Explain decisions in a clear, human way.',
        category: 'Transparency',
        difficulty: 'intermediate',
      },
      {
        id: 'ai-ethics-4',
        hook: 'Safety Rails',
        meat: 'Add guardrails to reduce harmful outputs, and monitor real-world behavior after launch.',
        simplified: 'Build safety limits and keep watching after release.',
        category: 'Safety',
        difficulty: 'intermediate',
      },
      {
        id: 'ai-ethics-5',
        hook: 'Governance',
        meat: 'Define accountability: who approves, audits, and stops risky models. Document decisions.',
        simplified: 'Make clear who is responsible and keep records.',
        category: 'Governance',
        difficulty: 'intermediate',
      },
      {
        id: 'ai-ethics-quiz',
        isQuiz: true,
        hook: 'Quiz Time!',
        meat: 'Test your knowledge',
        quizQuestion: 'What is the best first step before using personal data?',
        quizOptions: ['Collect everything', 'Get clear consent', 'Hide the source', 'Avoid documentation'],
        quizAnswer: 1,
        category: 'Quiz',
        difficulty: 'beginner',
      },
    ],
  },
  {
    id: 'prebuilt-climate-tech-now',
    title: 'Climate Tech Now',
    description: 'Key technologies shaping decarbonization, from clean power to resilience.',
    createdAt: now,
    updatedAt: now,
    cards: [
      {
        id: 'climate-1',
        hook: 'Electrify',
        meat: 'Switching cars and buildings to electricity enables clean power to cut emissions.',
        simplified: 'Use electricity instead of burning fuels.',
        category: 'Mitigation',
        difficulty: 'beginner',
      },
      {
        id: 'climate-2',
        hook: 'Heat Pumps',
        meat: 'Heat pumps move heat efficiently, reducing energy use versus gas heating.',
        simplified: 'Heat pumps heat and cool with less energy.',
        category: 'Buildings',
        difficulty: 'beginner',
      },
      {
        id: 'climate-3',
        hook: 'Grid Storage',
        meat: 'Batteries and other storage smooth renewable supply when the sun or wind drops.',
        simplified: 'Storage keeps power available when renewables dip.',
        category: 'Energy',
        difficulty: 'intermediate',
      },
      {
        id: 'climate-4',
        hook: 'Carbon Removal',
        meat: 'Direct air capture and nature-based sinks can remove residual emissions.',
        simplified: 'Some tech and ecosystems pull CO2 back out.',
        category: 'Carbon',
        difficulty: 'intermediate',
      },
      {
        id: 'climate-5',
        hook: 'Adaptation',
        meat: 'Resilience upgrades like flood control and cooling centers reduce climate impacts.',
        simplified: 'Prepare cities and systems for heat and storms.',
        category: 'Resilience',
        difficulty: 'beginner',
      },
      {
        id: 'climate-quiz',
        isQuiz: true,
        hook: 'Quiz Time!',
        meat: 'Test your knowledge',
        quizQuestion: 'Why is grid storage important for renewables?',
        quizOptions: ['It increases fuel use', 'It smooths supply gaps', 'It makes power cheaper instantly', 'It removes CO2 directly'],
        quizAnswer: 1,
        category: 'Quiz',
        difficulty: 'beginner',
      },
    ],
  },
  {
    id: 'prebuilt-cybersecurity-basics',
    title: 'Cybersecurity Basics',
    description: 'Essential habits to protect accounts, devices, and data.',
    createdAt: now,
    updatedAt: now,
    cards: [
      {
        id: 'cyber-1',
        hook: 'Phishing',
        meat: 'Attackers trick people into clicking fake links or sharing secrets. Verify before acting.',
        simplified: 'Scammers use fake messages. Double-check.',
        category: 'Threats',
        difficulty: 'beginner',
      },
      {
        id: 'cyber-2',
        hook: 'MFA',
        meat: 'Multi-factor authentication blocks many account takeovers even if a password leaks.',
        simplified: 'Add a second step to log in.',
        category: 'Defense',
        difficulty: 'beginner',
      },
      {
        id: 'cyber-3',
        hook: 'Patching',
        meat: 'Updates fix known vulnerabilities. Delays keep doors open for attackers.',
        simplified: 'Install updates to close security holes.',
        category: 'Defense',
        difficulty: 'beginner',
      },
      {
        id: 'cyber-4',
        hook: 'Least Privilege',
        meat: 'Give users only the access they need. Less access means less damage.',
        simplified: 'Only give the minimum access needed.',
        category: 'Policy',
        difficulty: 'intermediate',
      },
      {
        id: 'cyber-5',
        hook: 'Backups',
        meat: 'Regular offline backups reduce ransomware impact and speed recovery.',
        simplified: 'Keep safe copies of important data.',
        category: 'Recovery',
        difficulty: 'beginner',
      },
      {
        id: 'cyber-quiz',
        isQuiz: true,
        hook: 'Quiz Time!',
        meat: 'Test your knowledge',
        quizQuestion: 'What is the best defense if a password is stolen?',
        quizOptions: ['Reuse it elsewhere', 'Enable MFA', 'Turn off updates', 'Share it with a friend'],
        quizAnswer: 1,
        category: 'Quiz',
        difficulty: 'beginner',
      },
    ],
  },
]
